### ISSUE TITLE
服务端的server是yjs自己默认的源码吗？

### ISSUE THREAD

**Issue by milu2003** [hughfenghen/y-editorjs#7]
我一直没看懂是怎么初始化编辑器的block数据的。
也就是假如编辑器初始状态有20个block的话，当加载yjs时，没看见你在哪里初始化这些数据。
![image](https://user-images.githubusercontent.com/15957433/112709408-512cff80-8ef4-11eb-840d-04340acbbe44.png)

我看见你代码就写了一串判断，那么 this.yArray  的数据是在哪初始化的，服务端吗

**Comment by milu2003** [comment]
找到答案了

```
wsProvider.once('synced', x => {
       console.log('数据已经同步');
});
```

估计需要做个步骤，判断第一个启动的用户从数据库读取编辑器的内容，然后设置初始值。

**Comment by milu2003** [comment]
https://discuss.yjs.dev/t/how-to-fetch-init-data-in-server-side/158/2

**Comment by milu2003** [comment]
我觉得editorjs这玩意一开始就没设计成多人实时协同。最近转而用prosemirror了，实时协同是相当不错的。而且历史修改记录这些功能也是做得很好。

editorjs最大的硬伤在于，每次只能更新整体的block，一个block里面可能含有多个层级的dom，数据一变更，刷新这个dom就造成了闪屏。

但是prosemirror设计得非常好，只是更新有数据变动的dom。

就拿代码高亮这个功能来说，在editorjs，你要做个带语法高亮的代码编辑器功能比较麻烦。但是prosemirror就很简单。
可以看看他的实现方式：https://www.tiptap.dev/code-highlighting

所以最近转而用 prosemirror 了

**Comment by hughfenghen** [comment]
@milu2003 prosemirror很老牌了，做成熟产品挺好的。
prosemirror接触了一点点
我觉得不好的地方，是api 、数据结构太复杂了。

实时协同，数据模型你怎么设计的？

**Comment by hughfenghen** [comment]
当时调研editor.js是想使用组件化的方式来描述富文本（一个 Block 就是一个组件，Block 嵌套描述为组件嵌套）
editor.js 将数据拆成 Block结构，数据库可以按 Block 级别存储，协同、增量更新时候应该会比较方便
可惜现在不做这一块了。

**Comment by milu2003** [comment]
> 当时调研editor.js是想使用组件化的方式来描述富文本（一个 Block 就是一个组件，Block 嵌套描述为组件嵌套）
> editor.js 将数据拆成 Block结构，数据库可以按 Block 级别存储，协同、增量更新时候应该会比较方便
> 可惜现在不做这一块了。

你是被editor带入坑了。
一开始我觉得prosemirror很复杂，弄了几天一点头绪也没有。
我不明白为什么作者设计得这么复杂难用。
当我用editor开发到多人实时协作和版本历史追踪修改、撤销。我发现editor根本无从下手，是因为他们设计的时候没考虑这个。未来估计也不可能有这个。
prosemirror之所以复杂，那是因为他必须解决协同的问题。比如多人实时协作，你如何做撤销功能？看起来很简单的功能，涉及到多人就复杂了。

比如editor的block方案，block里面有一个表单，如果多人协作，别人修改了这个表单里面的第三个文本框，你正在编辑第四个文本框，界面怎么同步刷新，甚至光标都同步，editor就歇菜了，无从下手。但prosemirror能同步光标，能局部刷新dom，这就是人家为什么复杂的原因了。


而且prosemirror可定制化非常强。

**Comment by milu2003** [comment]
至于数据库存储，其实prosemirror的每一个操作都可以看做一个步骤，你添加数据，修改时间，删除数据都是一个步骤。

```
{
  “stepId”: 1,
  “step”: {
    “stepType”:”replace”,
    ”from”:2,
    ”to”:2,
    ”slice”: {
      “content”:[{
        “type”:”text”,
        ”text”:”h”
      }]
    }
  },
  “clientID”: “1111–42783748297342”,
  “timestamp”: “Sun Feb 10 2019 12:31:32 GMT-0500 (Eastern Standard Time)”
}
```


![image](https://user-images.githubusercontent.com/15957433/113001180-24eada80-91a3-11eb-99ab-54699c9644f7.png)

每一个步骤都记录时间和作者和修改内容，存储到数据库里面，就能还原整个文档的修改记录，还能撤销操作。

> editor.js 将数据拆成 Block结构，数据库可以按 Block 级别存储，协同、增量更新时候应该会比较方便


这个其实不用担心，editor的方式也没有什么优势。
 
参考阅读：https://open.nytimes.com/we-built-collaborative-editing-for-our-newsrooms-cms-here-s-how-415618a3ec49

**Comment by milu2003** [comment]
其实editor的block，其实用prosemirror实现也不难。现在block笔记是很流行，notion带动了这玩意，但是很多文本编辑场景其实也没必要搞成那样。

这种block其实也有一定的局限。

比如，跨选区选择文本。我想复制第二个block的一段文字和第三个block的全部文字，使用block只能选中所有的block：

![image](https://user-images.githubusercontent.com/15957433/113003809-a9d6f380-91a5-11eb-9858-64bde1a3c84f.png)

比如下面这样：

![image](https://user-images.githubusercontent.com/15957433/113004001-d4c14780-91a5-11eb-9682-736617f49d3c.png)

才是正常的，当然，这也不算什么大毛病，但是也没必要为了block而block。

你可以看看飞书文档的实现：

![image](https://user-images.githubusercontent.com/15957433/113004673-5d3fe800-91a6-11eb-85e9-7c82c9c31223.png)


他也算block的方式，但是他又不像block。

**Comment by milu2003** [comment]
editor的事件设计得也不好。我开发的时候经常遇到事件的问题。ProseMirror做得就非常好了，具体区别在哪，我暂时研究得也不深。

**Comment by milu2003** [comment]
编辑器太复杂了，特别是协同这块，而协同功能是我们产品的主打功能，当初就不应该用editor来做，以为editor是刚出来不久的，这种主流编辑器必备的协同他们应该会考虑到。
prosemirror太复杂了点，很多教程完全看不懂，最近直接啃官方的源码了，再难啃也要啃。一点点的调试，一点点的分析它的源码。

**Comment by milu2003** [comment]
prosemirror这玩意的数据存储是怎样的呢？

```js
// read the initial document (or have it somewhere)
let document = Node.fromJSON(schema, json);
// go through all steps you recieved from a client (probably serialized as json)
for (let jsonStep of steps) {
    // get the step from json
    const step = Step.fromJSON(schema, jsonStep);
    const result = step.apply(document)
    if (result.failed) {
     // step did not apply
    } else {
       document = result.doc;
    }
}
```
一开始初始化一个文档，然后再把每一个步骤追加上去，形成一个完整的文档数据。

打个比方，一篇文章一开始就是一个空白的文档，经过了2000个步骤之后，形成了一篇文章。
如果你要展现这篇文章的最终内容，其实只需要存储这2000个步骤的数据，然后再追加上去就行了。
这样也可以方便的回溯版本，也可以看出每一步的变化。

比如我回溯到第1000个步骤的状态，也可以看第1000步和第10001步的区别。

这样是不是比editor的block数据优秀得多了？

我研究了一下notion，当你输入一个字母 a 时，就会像后台发送这样的数据

![image](https://user-images.githubusercontent.com/15957433/113022913-b401ed80-91b7-11eb-93b1-b80cf808758d.png)


其实也是一个step。

editor的block呢？我感觉没有这样的设计。UI形似block，但底层的数据结构并不是为协作而生。

**Comment by milu2003** [comment]
https://user-images.githubusercontent.com/15957433/113650038-2431d700-96c2-11eb-89b6-450c31c551e0.mov


用 prosemirror 重构了项目，现在多人实时协同，体验非常好。 并不是整个block整体刷新。
